name: Run Test Case

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Get XML
      id: getxml
      uses: mavrosxristoforos/get-xml-info@1.0
      with:
        xml-file: 'CSharp.lua.Launcher/CSharp.lua.Launcher.csproj'
        xpath: "//TargetFramework/substring-after(., 'net')"
    

    - run: echo "${{ steps.getxml.outputs.info}}.x"

    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: clear
      run: dotnet clean --configuration Debug && dotnet nuget locals all --clear
    - name: Build with dotnet
      run: dotnet build --configuration Debug
    - name: Run Test Case
      run: cd test/ & test
      shell: cmd
